### ISSUE TITLE
Demo removeItems blanks view

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#1]
When using the `removeItems` method of omnitable as example action, the omnitable content is blank afterwards.

Regrouping returns the content.

**Comment by plequang** [comment]
This is been solved in cosmoz-grouped-list (https://github.com/Neovici/cosmoz-grouped-list/commit/91979ae108d0de4e5045c24c6d025701839134c3)

Now removing items do not require to re-sort/re-group the data.
