### ISSUE TITLE
Amount without currency should be considered as invalid

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-omnitable#111]
# Description

In `column-omnitable-column-amount`, the `toValue` function use the default currency for values that do not have a `currency` property.

But in `renderValue`, values without currency will be rendered as empty string.

We must rather handle values without currency as invalid values, so that:
* toValue  should return null 
* renderValue should render the string "Invalid value" (translated)

The purpose of default currency is to have a reference currency used when sorting amounts with mixed currency => this is not implemented yet.

**Comment by megheaiulian** [comment]
@programmer4web Change `toAmount` in `omnitable-column-amount` so that it doesn't accept anything without currency. After changing that some other parts will need to change and we should also store the currency in URL.
