### ISSUE TITLE
Replace JaySunSyn/datetime-local with Neovici/cosmoz-datetime-input

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-omnitable#116]
Currently, we are https://github.com/JaySunSyn/datetime-local component to render datetime values.
We should replace it with Neovici/cosmoz-datetime-input

**Comment by JaySunSyn** [comment]
can be closed

**Comment by nomego** [comment]
Did you remove your comment? Looking at bower.json we still use your repo.

**Comment by JaySunSyn** [comment]
Yes, removed it. Thought that already has been done..

**Comment by JaySunSyn** [comment]
Oh.. Didn't see this one. https://github.com/Neovici/cosmoz-omnitable/pull/124
