### ISSUE TITLE
Broken XLSX

### ISSUE THREAD

**Issue by MickeBerggren** [Neovici/cosmoz-omnitable#122]
Downloaded xlsx files still trigger error/corrupt message on *Mac* excel. 

See previous issue: https://github.com/Neovici/nullxlsx/issues/2

**Comment by JaySunSyn** [comment]
Sorry for that! The build was not updated. Should get fixed with https://github.com/Neovici/nullxlsx/pull/3

**Comment by nomego** [comment]
Fixed @MickeBerggren ?
Feels related to #123 and maybe Neovici/cosmoz-image-viewer#51 ?

**Comment by MickeBerggren** [comment]
Yes
