### ISSUE TITLE
Limit "From date" YYYY field to 4 characters in Due date omnitable column

### ISSUE THREAD

**Issue by fredrikbernholm** [Neovici/cosmoz-omnitable#130]
Its now possible to enter 6 characters for "YYYY" in the "From date" field for _Due date_ in omnitable. The marker will thus not jump automatically from year to month in the "From date" field as it does in the "Until date" field, and as in every other date field.

**Comment by fredrikbernholm** [comment]
Seems like I can't assign issues for some reason. But I'm assigning this to you @megheaiulian.

**Comment by megheaiulian** [comment]
Hi, 
Can you provide some steps to reproduce the issue? I am unable to input more than 4 characters in Chrome because it is a native date input.
What browser are you using ?

**Comment by fredrikbernholm** [comment]
Strange, the issue has been there quite a while, and still was yesterday. But now its gone... So I guess we can close this issue.

**Comment by megheaiulian** [comment]
@fredrikbernholm On Firefox this does seem to happen. Can you check again ?

**Comment by fredrikbernholm** [comment]
The problem is gone in Chrome at least, that's what matters I guess?
