### ISSUE TITLE
Default sorting in "Invoice archive" stops at 2017

### ISSUE THREAD

**Issue by fredrikbernholm** [Neovici/cosmoz-omnitable#139]
The default sorting in "Invoice archive" doesn't show invoices from 2018, even though they exist and show up when searching in the invoice date column.

**Comment by megheaiulian** [comment]
@fredrikbernholm This isn't a bug in omnitable. When getting invoices from the API there is no sorting info passed to the server and only `250` out of `4211` invoices are grabbed.
They are then sorted locally in omnitable.

**Comment by nomego** [comment]
Actually the APIs seem to support 
```
orderByField
orderByDescending
```
So we could extend OTS to ask backend to sort the results we _do_ get.

**Comment by megheaiulian** [comment]
@nomego This would then be a frontend issue and support must be added search helper?

**Comment by nomego** [comment]
Yes, to sync the omnitable sort setting with the ots params. It might be tricky to generalize though, backend looks at header params mostly, etc. But we could try.
