### ISSUE TITLE
Template re-rendering

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#14]
Templates doesn't seem to re-render properly.

This can be observed by regrouping Omnitable:

![image](https://cloud.githubusercontent.com/assets/960553/23056095/e3067ad4-f4e9-11e6-9665-18644249e437.png)

### To reproduce

1. Run the 'full-demo' (demo/full-demo.html)
2. Group the omnitable on something (Name)
3. Re-group the omnitable on something else (Group)

Regrouping a second time also makes group header templates stuck:

![image](https://cloud.githubusercontent.com/assets/960553/23056166/5a8dfdca-f4ea-11e6-8307-f4e84125c014.png)

**Comment by plequang** [comment]
This has been solved in https://github.com/Neovici/cosmoz-grouped-list/issues/2
