### ISSUE TITLE
Properly flex out all column headers

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#15]
Does not work properly for at least amount and number

**Comment by plequang** [comment]
Sorry, I don't understand the issue here. 
headers are all `flex: 1` by default, and get later a fixed sized based on the first rendered item.
If no items are rendered (because no data, or only collapsed groups), then column headers revert to the default `flex: 1`  sizing.

**Comment by nomego** [comment]
I think this was solved in an earlier commit.
