### ISSUE TITLE
Bug, column filtering inside cz-privileges does not change table contents

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-omnitable#169]
The column header filtering does not work in the cz-privileges component used in the user group administration view. It does not respond on changes, nothing happens in the table.

To reproduce, do this:

1. Go to https://alpha.cosmoz.com/
2. Administration -> Groups -> Group lists
3. Select a group with items in the Group Access tab table
4. Go to the Group Access tab
5. Fill in something in the Role column header or select something that does not exist in the table

I am not sure if this is related to cz-privileges at all, but this was the only place where I could locate the problem.

This may be the same as or related to https://github.com/Neovici/cosmoz-omnitable/issues/169.

**Comment by plequang** [comment]
Wrong project

**Comment by dotpointer** [comment]
But problem is in cosmoz-omnitable inside cz-privileges?

**Comment by plequang** [comment]
I've moved this issue to cosmoz-frontend https://github.com/Neovici/cosmoz-frontend/issues/222 because it refers to an internal component.
And you already created an issue in cosmoz-omnitable for the underliying issue https://github.com/Neovici/cosmoz-omnitable/issues/170#issuecomment-381087908

**Comment by dotpointer** [comment]
Ok.
