### ISSUE TITLE
Bug, filtering boolean column on No does not filter out Yes rows

### ISSUE THREAD

**Issue by dotpointer** [Neovici/cosmoz-omnitable#170]
Selecting No in column header in a boolean column does not filter out Yes alternatives.

To reproduce the problem:

1. Login to beta
2. Go to Administration -> List users
3. In the Active column, select No
4. Rows with Yes still are in the table

This may be related to or the same as https://github.com/Neovici/cosmoz-omnitable/issues/169 but in differ from that issue this table responds to column header filter changes and updates its content.

**Comment by plequang** [comment]
Yes, there is a bug in cosmoz-omnitable-column-boolean filtering on the `false` value.

**Comment by dotpointer** [comment]
Is there a repository for cosmoz-omnitable-column-boolean that I do not have access to where this should be moved to then?

"0 results for repositories matching cosmoz-omnitable-column-boolean"

**Comment by plequang** [comment]
This should not be moved.  `cosmoz-omnitable-column-boolean` is in this repo.
And this is a valid bug.

**Comment by dotpointer** [comment]
Sorry, commented in the wrong issue.
