### ISSUE TITLE
Filtering with hidden decimals

### ISSUE THREAD

**Issue by JockeCK** [Neovici/cosmoz-omnitable#176]
In number columns we show a certain amount of fractions visually. Variable "minimumFractionDigits"

However the fractions are still there and can fool the user depending on how the filter is used.
Example:
46,768 is the number, lets say this is an currency amount and two fractions are shown.
That is as 46,76

The user sets both to and from filter as 46,76.

This results that at least not the row with the value 46,768 is not shown. It interprets the maximum allowed value as 46,760. 

So we need to take this into consideration in the range behavior. 

Top of my head solution would be to round the comparison value during comparisons according to "minimumFractionDigits". Or maybe just multiply both sides of the equation with an nice large number and call it a day.

Any thoughts @nomego ?

(RM #18323)

**Comment by megheaiulian** [comment]
@nomego @JockeCK I think the best solution is to round according to `minimumFractionDigits` in the comparison function as suggested by @JockeCK.

**Comment by nomego** [comment]
Sounds good, want to pr it?

**Comment by programmer4web** [comment]
[WIP] writing an test to replicate. Then apply / implement fix.
