### ISSUE TITLE
multi-select

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#177]
Selecting an item in omnitable, then holding down shift and selecting another item further down the list, should also select all items in between

(See multi-select in Gmail)

**Comment by plequang** [comment]
Should this reproduce gmail behavior ?

1. Range goes from last selected item to item clicked with shift.
2. The range is selected (or deselected) if the (last) item clicked with shift is toggled selected (or deselected)

**Comment by megheaiulian** [comment]
We could do an initial implementation like this:

- [ ] Shift + click -> extend the current selection if it exists to the current item (down or up)
- [ ] Ctrl + click -> select only this item
- [ ]  Ctrl + Shift + click -> select everything but this item
- [ ]  Alt+ click -> select everything from top the current item
- [ ] Ctrl + Alt + click -> select everything from bottom to the current item

Note: Grouping might make this a bit more complicated ...

**Comment by megheaiulian** [comment]
Initially it makes sense to implement Shift + click, and Ctrl + click only.
