### ISSUE TITLE
bottom-bar popup menu weirdnesses

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#2]
Popup menu in omnitable bottom-bar appears quite a bit away from the triggering button.

Also looks weird but that might be more of a bottom-bar issue...

![screenshot_20160310-083602](https://cloud.githubusercontent.com/assets/960553/13670231/fc7158c0-e6c8-11e5-8add-fda8d967de5e.png)

![screenshot_20160310-083609](https://cloud.githubusercontent.com/assets/960553/13670265/26271772-e6c9-11e5-9de5-894eea6c0b45.png)

**Comment by plequang** [comment]
Fixed in cosmoz-bottom-bar
