### ISSUE TITLE
Folded columns/values styling

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#201]
How do we adjust the styling in the folded values/columns? (`cosmoz-omnitable-item-expand-line`).
For `cosmoz-treenode` (`cosmoz-omnitable-treenode-column`) values, the styling should line-break (not `no-wrap`).

**Comment by nomego** [comment]
Well only in folded mode, not when in a regular cell.

**Comment by cristinecula** [comment]
@nomego I'm not sure how it should look like. Is this OK?

![2019-03-20-161228_424x470_scrot](https://user-images.githubusercontent.com/710155/54690955-2781b680-4b2b-11e9-95c1-d1333a7c9146.png)
![2019-03-20-161203_929x472_scrot](https://user-images.githubusercontent.com/710155/54690957-281a4d00-4b2b-11e9-9228-9f5a6395432b.png)

**Comment by nomego** [comment]
@Neovici/uiux is the above ok?
@cristinecula do we have a "before" image?

**Comment by sanlifer** [comment]
Could the column headline (Node) be adjusted top left instead of centered left? Would be easier to read in my opinion.

**Comment by cristinecula** [comment]
@nomego this is what it looks like without this commit
![2019-04-04-144417_423x518_scrot](https://user-images.githubusercontent.com/710155/55553184-31d5b000-56e8-11e9-9fa2-1554df9d3d35.png)

**Comment by cristinecula** [comment]
@sanlifer does this look OK?

![2019-04-04-150300_444x433_scrot](https://user-images.githubusercontent.com/710155/55554162-c80ad580-56ea-11e9-8f9c-7855ee5155f1.png)

**Comment by sanlifer** [comment]
@cristinecula Looks good!
