### ISSUE TITLE
Inserted from value not remaining in unmatched quantity column

### ISSUE THREAD

**Issue by sanlifer** [Neovici/cosmoz-omnitable#207]
Unmatched invoice rows view (queue)
Unmatched quantity column

When inserting a value in the to and/or from in the interval selection box, the number immediately skips back to "From" or "To", instead of remaining in the input field. User can't press enter or any other action to keep the inserted number in place, and the table is not sorted according to the selection.

Same column in other views do not have this kind of behaviour.

**Comment by megheaiulian** [comment]
@sanlifer I do not manage to replicate this issue. Can you let me know what amount are you using for testing ?
