### ISSUE TITLE
Empty ot, iron-list scroll

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#21]
![row-highlight-empty-ot](https://user-images.githubusercontent.com/960553/27002241-04b9bd2a-4ddd-11e7-9779-877f0468b2e5.png)
![inspector-empty-ot](https://user-images.githubusercontent.com/960553/27002242-04beddfa-4ddd-11e7-998c-bdfb7e2bdbd1.png)

**Comment by plequang** [comment]
This is fixed since removal of warm up feature in cosmoz-grouped-list.
