### ISSUE TITLE
2 date selectors open simultaneously/overflowing in OT

### ISSUE THREAD

**Issue by sanlifer** [Neovici/cosmoz-omnitable#225]
![skarmavbild 2018-09-12 kl 11 26 50](https://user-images.githubusercontent.com/31737905/45415885-ef328480-b67e-11e8-9c3d-dad594802e12.png)

With one date selector still open, ("Arrival date") I was able to open another selector simultaineously ("Due date") when using tab+arrow right. 

See attached image.

**Comment by cristinecula** [comment]
The bug originates from `<paper-autocomplete>`.
I have submitted a fix https://github.com/ellipticaljs/paper-autocomplete/pull/136.

**Comment by cristinecula** [comment]
Fixed by https://github.com/Neovici/paper-autocomplete/pull/9
