### ISSUE TITLE
Add proper currency management in cosmoz-omnitable-column-amount

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#24]
- [ ] Configurable base currency
This will be used when showing the filter menu
- [ ] Auto-detectable base currency
Most frequently occurring currency in one (or all combined?) amount columns
- [ ] Sorting algorithm based on amount value instead of amount number (through currency conversion from neovici/cosmoz-behaviors#1 - replace "TODO: fx" comments)

**Comment by JaySunSyn** [comment]
@nomego is this issue still active?

If so, I would love to hear a bit more about it.

**Comment by nomego** [comment]
This issue is still active, tried to make the description clearer.
Let me know if there still are questions!

**Comment by programmer4web** [comment]
@nomego currently in the PR auto-detect defaultCurrency runs if it is not already configured by attribute/property. I think there are cases when omnitable data changes and the defaultCurrency needs update for the new set of data. But in this case I think we need an Boolean property updateDefaultCurency (true/false) to know if we keep the pre-configured defaultCurrency or auto-detect for the new set of data. Is this needed?
