### ISSUE TITLE
Consolidate autocomplete/list behavior

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#247]
There is a lot of overlapping/duplicate logic between autocomplete, list and list-horizontal.
Basically what list and list-horizontal tries to do is exactly the same as autocomplete, except:
* They have unique cell templates
* `values` is two-dimensional which needs to be considered when
  * Making a unique suggestions list for paper-autocomplete-chips
  * When filtering (`_applyMultiFilter`)

Probably easier to do when we are class-based. (#246)
list can extend autocomplete and just add two-dimensional value handling, and list-horizontal can extend list and just override the cell template. (https://polymer-library.polymer-project.org/2.0/docs/devguide/dom-template#insertcontent)

**Comment by dotpointer** [comment]
I have a strong feeling that this should not be done in Polymer anymore but in Haunted or possibly not be done at all.

@megheaiulian, @cristinecula or @nomego - have a look and check what should be done here?

**Comment by nomego** [comment]
Yeah let's go haunted first before tackling this
