### ISSUE TITLE
Column resizing doesn't work properly on Chrome dev 60-63

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#25]
Some change in Chrome has broken the column resizing in beta (60)/dev (61) versions.

Estimated release date is - [Aug 1st, 2017 (July 26th for Desktop)](https://www.chromium.org/developers/calendar), we need to have it solved by then.

**Comment by plequang** [comment]
There had been a lot of changes in cosmoz-omnitable and cosmoz-grouped-list, affecting rendering of header and rows.

Tested on Chrome 61 on windows and cannot reproduce.

**Comment by nomego** [comment]
Still experiencing this a lot.

Can not reproduce with Chromium Version 60.0.3112.78 (Developer Build) Built on Ubuntu , running on Ubuntu 17.04 (64-bit) but easily with Google Chrome Version 61.0.3141.7 (Official Build) dev (64-bit)

The Google Chromebox at the office is also showing this and others at the office has been reporting it too.

**Comment by nomego** [comment]
Seems like it's only available in the dev channel on Linux or beta on Chromebox.

**Comment by megheaiulian** [comment]
@nomego I have Linux and can test this again on all Chrome, Chromium channels.

**Comment by cristinecula** [comment]
I don't think this is relevant anymore.
