### ISSUE TITLE
Add eslint comma-dangle rule

### ISSUE THREAD

**Issue by cristinecula** [Neovici/cosmoz-omnitable#254]
Actually I was under the impression that dangling commas could cause issues outside of IE8, but if that's not the case maybe we should rather enable/enforce it for multi-line arrays/objects (and also prevent it in all other cases).

_Originally posted by @nomego in https://github.com/Neovici/cosmoz-omnitable/pull/253_

```json
"comma-dangle": [
	"error",
	{
		"arrays": "always-multiline",
		"objects": "always-multiline",
		"imports": "never",
		"exports": "never",
		"functions": "ignore"
	}
],
```

**Comment by nomego** [comment]
This has been decided against, any further eslint rule changes should be against https://github.com/Neovici/eslint-config
