### ISSUE TITLE
Omnitable 2.x perf improvements

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#261]
#258:
> [...] but there are more performance improvements possible (for example: item-expand should render the columns only when expanded).[..]

**Comment by cristinecula** [comment]
I'm currently investigating memory leaks for these use-cases:
* setting lots of data, then setting empty data
* detaching a filled cosmoz-omnitable

**Comment by cristinecula** [comment]
## Profile Scenario:
1. open http://127.0.0.1:8081/components/cosmoz-omnitable/demo/full-demo.html
2. empty and generate new data a few times
3. garbage collect
4. start recording profile
5. repeat a few times:
5.1. generate and empty data a few times, making sure to end with empty data
5.2. garbage collect
5. stop recording

Result:
![snapshot1](https://user-images.githubusercontent.com/710155/54271767-d4d45780-458a-11e9-8696-5461951882b6.png)

If you look at memory allocation you can see how it increases when generating data and how it decreases abruptly when garbage is collected. After each repeat of step 3 the document, node and listener counts remains the same. This means that no DOM elements or event handlers are leaked in this scenario.

## Heap snapshot scenario:
1. open http://127.0.0.1:8081/components/cosmoz-omnitable/demo/full-demo.html
2. empty and generate new data a few times
3. garbage collect
4. save snapshot
5. repeat a few times:
5.1. generate and empty data a few times, making sure to end with empty data
5.2. garbage collect
5.3. save snapshot

Results:

The TemplateInstances created by TemplatizeMixin remain constant across snapshots.
![Screenshot from 2019-03-13 12-40-54](https://user-images.githubusercontent.com/710155/54272898-457c7380-458d-11e9-9a39-28249f0d12e0.png)

This means that template instances management is OK and they are re-used efficiently.

[snapshots.zip](https://github.com/Neovici/cosmoz-omnitable/files/2960932/snapshots.zip)

**Comment by cristinecula** [comment]
## Profile Scenario:

1. open http://127.0.0.1:8081/components/cosmoz-omnitable/demo/full-demo.html
2. resize the window a few times to min/max size
3. garbage collect
4. start recording profile
5. repeat a few times:
5.1. resize the window a few times to min/max size
5.2. garbage collect
6. stop recording

Results:
![Screenshot from 2019-03-13 13-50-31](https://user-images.githubusercontent.com/710155/54277151-b45eca00-4597-11e9-8d72-989457499f28.png)
After garbage collection node and listener counts remain the same.

[Profile-resize.zip](https://github.com/Neovici/cosmoz-omnitable/files/2961318/Profile-resize.zip)

**Comment by nomego** [comment]
Closing, more work done after 3 upgrade
