### ISSUE TITLE
Upgrade FileSaver.js

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#262]
In the git history we stayed with FileSaver 1.3.4 cause 1.3.6 was broken (9fee62c9b00a362fda6756dd4af66e5606ad8b63).

According to https://github.com/eligrey/FileSaver.js/releases, 1.3.6 "fixed"  (https://github.com/eligrey/FileSaver.js/issues/408) where 1.3.8 reverted it.

Was that the issue that broke everything and is it now safe to go back to the latest version 2.0.0?

**Comment by nomego** [comment]
The issue was actually eligrey/FileSaver.js#409 but it should be resolved with v2.0.0, which we would upgrade to if we dropped the specific dep and let the filesaver import component handle the dependency.

**Comment by erayd** [comment]
@nomego I'm not convinced that #408 is fixed. Some filetypes work, and some (e.g. markdown) fail abysmally and simply cause Chrome to spawn a new tab at `about:blank#blocked` instead.

**Comment by nomego** [comment]
Fixed by Polymer 3 upgrade.
