### ISSUE TITLE
Using Omnitable as a search

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#27]
There are quite a few scenarios where is would be convenient to use Omnitable as a search component instead of just searching local data.

Right now we fetch data to work on and then the columns and filters base everything on retrieved data.

The idea would be something like:
- Connect the omnitable itself to a backend-call (_fetch-data_)
- Connect relevant columns to backend calls for possible values (fetch-possible-values)
- When writing in a header filter, omnitable will query backend for possible values for the given property
  - ex. "give me all possible `created_date` for the search query `2017-05-1`"
    - possibly this will also send existing filters to say "give me all possible `created_date` for the search query `2017-05-1` where `active=1`"
- Once something is selected in the header filter, the omnitable _fetch-data_ will query the backend for data
  - "give me all data with `created_date=2017-05-10&active=1`"

We should discuss the technical possibilities but also the optimal UX.

Sending to @plequang for feedback.

**Comment by nomego** [comment]
I have an idea to try out.. :)

**Comment by plequang** [comment]
Do. Or do not. There is no try.

**Comment by nomego** [comment]
Prototype is available and necessary functionality is in Omnitable today. Any specific bugs regarding this will be separate issues.
