### ISSUE TITLE
Removing a selected item clears selection

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#270]
Users use omnitable selection to create queues and then work in those.
After acting on an item so it's no longer applicable for the queue, the item is removed from omnitable.
This causes all selected items to be cleared, where the user expectation is that only the removed item should be cleared.

**Comment by cristinecula** [comment]
Repro:
> Well if you select a few items in an omnitable (among them the first), find omnitable in Elements in devtools, and do something like `$0.removeItem($0.data[0]);`
It should clear all checkboxes
(but really it shouldn't..)
> (@nomego via Slack)

**Comment by cristinecula** [comment]
@nomego the issue stems from cosmoz-grouped-list. I'll submit a fix there.

**Comment by nomego** [comment]
Closing in favor of https://github.com/Neovici/cosmoz-grouped-list/issues/41
