### ISSUE TITLE
Omnitable cells with link get a `[object Object]` title

### ISSUE THREAD

**Issue by loicwolff** [Neovici/cosmoz-omnitable#278]
When hovering a table cell with a link in them, the title for the cell is `[object Object]`.

I found similar closed issues regarding this:
- https://github.com/Neovici/cosmoz-omnitable/issues/158
- https://github.com/Neovici/cosmoz-omnitable/issues/179

**Comment by fredrikbernholm** [comment]
Is this fixed by any of your other commits @JockeCK ?

**Comment by fredrikbernholm** [comment]
(Sorry, this is even more general than the RM issue, so I guess this is covered?)

**Comment by JockeCK** [comment]
@loicwolff Do you have an example of this? I looked at an random view and the tool tip seemed to work there, even when there is an link connected.

**Comment by cristinecula** [comment]
@JockeCK was this fixed by https://github.com/Neovici/cosmoz-frontend/pull/1113 ?

**Comment by JockeCK** [comment]
> @JockeCK was this fixed by [Neovici/cosmoz-frontend#1113](https://github.com/Neovici/cosmoz-frontend/pull/1113) ?

Quite possible, that is why I wanted to check which views this had occurred in. but to make sure, I think testing will need to keep an eye out, will talk to them about it.

**Comment by loicwolff** [comment]
> @loicwolff Do you have an example of this? I looked at an random view and the tool tip seemed to work there, even when there is an link connected.

It was on pretty much any cell with a link in it. I've browsed alpha a bit and couldn't repro anymore, so looks like it's fixed.

Should I close this issue or should I let a maintainer do it?

**Comment by JockeCK** [comment]
Great, knock on wood, I think we have found all cases. Closing the issue
