### ISSUE TITLE
Dynamic actions based on selected items

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#28]
When injecting actions based on selected items in omnitable, somehow the selection is cleared (but omnitable/grouped-list still shows the checkboxes checked).

See updated full demo from 3a007d03ce186c604bd7a3907bc9db490d8149d8

**Comment by JaySunSyn** [comment]
@nomego Hi, would love to hear more about this issue.

I fixed the demo here https://github.com/Neovici/cosmoz-omnitable/pull/31 and do not see such behavior. But maybe I also don't fully understand it.

**Comment by nomego** [comment]
Actually I think I solved this with 9c6c160aa8430e824c4c2a72d19f502732c9ebf6 and forgot to update this case. Oops!
