### ISSUE TITLE
Rework boolean column

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#315]
UI/UX has concluded that the boolean column should behave a bit differently.

Instead of the current `paper-dropdown-menu`/ `paper-listbox` elements, we should have a `paper-autocomplete` much like https://github.com/Neovici/cosmoz-omnitable-treenode-column.

The suggestions list should contain the true/false labels, when selecting an option it should fill the input (like treenode-column).

**Comment by dotpointer** [comment]
Pull request with tests merged. Please check if the changes are filling the requirements or if more needs to be done.

**Comment by dotpointer** [comment]
@cristinecula found more things to do with this, noted in #335.

**Comment by dotpointer** [comment]
Additional fixes in #340 has been merged. Ready for review.

**Comment by dotpointer** [comment]
Commits are merged and active and it has been removed from review in progress. I conclude that it is done then.
