### ISSUE TITLE
Rename `dataTemplate` property in `cosmoz-omnitable-column-behavior`

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-omnitable#32]
This is not a bug.
`cosmoz-omnitable-column-behavior` has a property named `dataTemplate`, used to set a custom template that will render a data cell.

When used in html, this property name create confusion with html `data-*` attributes, that are used to set values in the `dataset` property of HTML elements (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset).

Also, polymer linter currently considers all attributes starting with `data-` as dataset attributes.
https://github.com/Polymer/polymer-linter/issues/68

So this would be better to rename the dataTemplate property to something else, like `cellTemplate`.

This will be a breaking change for the component, so I guess the sooner the better.

**Comment by JaySunSyn** [comment]
@plequang can be closed

**Comment by JaySunSyn** [comment]
@plequang can be closed

**Comment by plequang** [comment]
Fixed by PR #34
