### ISSUE TITLE
Restore editable function

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#35]
Restore the editable demo while fixing any issues with editables.

Ideally, the demo should showcase items being fed to omnitable, edited, and items being updated while changes are being made.
We probably want to fire some "item-changed" event as well.

**Comment by JaySunSyn** [comment]
can be closed

**Comment by nomego** [comment]
Closed by #52.
Please write "Fixes #35" or similar in future PRs and it should auto-close this issue when merged.
