### ISSUE TITLE
Locale of Date/Time picker are browser or OS dependend

### ISSUE THREAD

**Issue by JaySunSyn** [Neovici/cosmoz-omnitable#53]
nomego: The date picker is controlled by the browser and Chrome won't let us control the date format, it is controlled by the OS locale. Our users want a certain format in the date picker even when the OS is configured for US locale. So we might have to abandon the date picker, and by extension, probably also the datetime-local picker, and find a new collection of elements not tied to the browser or OS.

**Comment by nomego** [comment]
We have actually decided to go the reverse way and embrace the os/browser locale. Users will *not* be able to choose a locale in the app but rather the app will adjust according to browser settings, as it should be.
