### ISSUE TITLE
Different behavior when searching for number ranges

### ISSUE THREAD

**Issue by SimonThunborg** [Neovici/cosmoz-omnitable#66]
If the user search for e.g amounts from 0 to 0 the search/filter automatically changes to 0 to 0.03. 
![omnitable - number range](https://user-images.githubusercontent.com/32709706/31764872-c583cdc4-b4c2-11e7-85a7-b7b7e344bd2d.png)

**Comment by nomego** [comment]
We need a way to reproduce this @SimonThunborg

**Comment by JockeCK** [comment]
Closing this after discussion with Simon. We could not reproduce it.
