### ISSUE TITLE
filter property of date column is readonly

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-omnitable#69]
In comoz-omnitable-date-behavior, the `filter` property is redefined as :
```js
filter: {
	type: Object,
	computed: '_computeFilter(_filterInput.start, _filterInput.end)'
},
```
this makes the `filter` property readonly, preventing users to set the filter from outside by binding to this property.
One should be able to bind to the filter property of date column the same way as other column types.

**Comment by nomego** [comment]
Agreed, although we should hold off this work until #59 is solved.
