### ISSUE TITLE
Grouping hides column filtering even though it's still active

### ISSUE THREAD

**Issue by sanlifer** [Neovici/cosmoz-omnitable#74]
If a user filters one of the Cosmoz omnitable columns and then group it on the same value, the filter is no longer visible in the column header, even though it's still active. 

When ungrouping, the selected filter reappears in the column header again. 

Once a column is filtered, it should be visible until the user removes it.

**Comment by nomego** [comment]
Hmm but if the users chooses to group on a filtered column, shouldn't we let them, but clear the filter for that column?

**Comment by sanlifer** [comment]
Say I've filtered on invoice date, a span of 3 months or so. And then I want to group it to see which invoices we're sent on what date (but only within my searched date span). Why would I want my filtering cleared?

**Comment by nomego** [comment]
Ah, true. So then it's a @Neovici/uiux case to decide how that is supposed to look, then.
Technically it's easier to just change a few rows of code to clear the filter rather.
Putting a new visible element in place to highlight the (hidden) filtering has more consequences.

**Comment by sanlifer** [comment]
Ok. I haven't seen the clients defect description, so if you think that doint the simpler solution will solve their issue with this then we could consider going with that.

**Comment by nomego** [comment]
Fixed through #73
