### ISSUE TITLE
Support Shadow DOM

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#9]
Trying the full-demo with Shadow DOM enabled (demo/full-demo.html?dom=shadow) breaks the row/cell rendering.

This should be fixed since we should use Shadow DOM whenever available and it will be default with WCv1 and Polymer 2.0

**Comment by plequang** [comment]
This is an issue in cosmoz-grouped-list. See https://github.com/Neovici/cosmoz-grouped-list/issues/1

**Comment by plequang** [comment]
This is fixed in https://github.com/Neovici/cosmoz-grouped-list/tree/perf-rework, used by next omnitable version https://github.com/Neovici/cosmoz-omnitable/tree/column-rework
